# Generated by Django 5.2 on 2025-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], max_length=50)),
                ('api_key', models.CharField(max_length=500)),
                ('document', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
