# Generated by Django 5.2 on 2025-04-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_documentanalysis_delete_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentanalysis',
            name='document',
            field=models.FileField(help_text='Supported formats: PDF, DOC, DOCX, TXT', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4', max_length=50),
        ),
    ]
