# Generated by Django 5.2 on 2025-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_documentanalysis_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentanalysis',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4', max_length=50),
        ),
    ]
