# Generated by Django 5.2 on 2025-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_documentanalysis_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentanalysis',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4.1-mini', 'GPT-4.1 Mini')], default='gpt-4.1-mini', max_length=50),
        ),
    ]
