# Generated by Django 5.2 on 2025-04-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_documentanalysis_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude AI')], default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('claude-3', 'Claude 3'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet')], default='gpt-4o', max_length=50),
        ),
    ]
