# Generated by Django 5.2 on 2025-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_documentanalysis_ai_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='analysis_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='report_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='token_usage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
