# Generated by Django 5.2 on 2025-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_documentanalysis_analysis_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentanalysis',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet'), ('claude-3-haiku-20240307', 'Claude 3 Haiku')], default='gpt-4o', max_length=50),
        ),
    ]
